apiVersion: v1
kind: Service
metadata:
  name: website-v1
spec:
  type: LoadBalancer
  ports:
  - port: 8050
    nodePort: 30304
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: website-v1
